algoritmo "algoritmo_contador_1ate10"

// Disciplina  : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Aula 10 – Estruturas de Repetição 2
// Autor(a)    : Juan Patrick
// Ano         : 2022

var

   //Variáveis inseridas pelo usuário
   contador: inteiro

inicio

      //Estrutura de repetição
      contador <- 1
      Repita
         Escreval (contador)
         contador <- contador + 1
      Ate (contador > 10)

fimalgoritmo
