algoritmo "algoritmo_contador_1ate10_3"

// Disciplina  : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Aula 11 – Estruturas de Repetição 3
// Autor(a)    : Juan Patrick
// Ano         : 2022

var

   //Variáveis inseridas pelo usuário
   contador: inteiro

inicio

      //Estrutura de repetição
      Para contador <- 1 ate 10 faca
         Escreval (contador)
      FimPara

fimalgoritmo
